config:
  log_path: ''
  bridges:
    default:
      class: '\Ermarian\EjabberdAuth\Bridge\HttpBridge'
      parameters:
        url: 'https://example.com/'
      hosts:
        - '*.example.com'
        - 'example.*'
        - 'example.com'
        - '.com'
        - '*'
