log_path: ''
bridges:
  default:
    class: '\Ermarian\EjabberdAuth\Bridge\HttpBridge'
    parameters:
      url: 'https://example.com/'
    hosts:
      - '*.example.com'
      - 'example.*'
      - 'example.com'
      - '.com'
      - '*'
  htpasswd:
    class: '\Ermarian\EjabberdAuth\Bridge\HtpasswdBridge'
    parameters:
      # Paths are relative to package root.
      file: 'htpasswd.txt'
    hosts:
      - 'htpasswd.example.com'
